name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v3
      
    - name: Update cache
      run: yes | yum -y --assumeyes makecache

    - name: Install build dependencies
      run: yes | yum -y --assumeyes install @'Development Tools' glibc-devel.i686 libgcc.i686 libstdc++-devel.i686 wget

    - name: Run build
      working-directory: ./AccuracyFix
      run: |
        # Export compiler include path
        export CPATH=$CPATH:/usr/include/c++/4.8.5/i686-redhat-linux

        # Make build
        make
    
    - name: Move release file to publish
      run: |
        # Make Match BOT path
        mkdir -p publish/addons/accuracyfix/dlls

        # Move released file to dlls
        mv ./AccuracyFix/Release/accuracyfix_mm.so publish/addons/accuracyfix/dlls

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: accuracyfix-linux
        path: publish/*